version: '3'
services:
  app:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=chickentendermarketplace.ca,www.chickentendermarketplace.ca
      - LETSENCRYPT_HOST=chickentendermarketplace.ca,www.chickentendermarketplace.ca
      - LETSENCRYPT_EMAIL=admin@chickentendermarketplace.ca
  db:
    restart: unless-stopped
  nginx-proxy:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    volumes:
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
